name:                cw
version:             0.1.0.0
github:              "ik1g19/cw"
license:             BSD3
author:              "ik"
maintainer:          "ik1g19@soton.ac.uk"
copyright:           "ik"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ik1g19/cw#readme>

dependencies:
- base >= 4.7 && < 5
- random
- deepseq

library:
  source-dirs: src

executables:
  cw-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cw

tests:
  cw-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cw
